### ISSUE TITLE
Limit tree depth or penalize long-running organisms

### ISSUE THREAD

**Issue by dbravender** [dbravender/gerl#1]
There should be an option to have tree depth and/or the time it takes for an organism to run to count against its fitness.

**Comment by robertdfrench** [comment]
Hey, that's brilliant! By forcing a tree depth restriction, we're placing a somewhat meaningless criterion on the potential solutions, but by rewarding speed... that is a very meaningful criterion.

The time needs to be calculated around the level of the initial gerl:evaluate() call, because some fitness tests (Like those I use to investigate card games) may actually run longer as a result of good performance from the organism (It keeps winning => It gets to play more rounds). 

However, by calculating the time from the initial gerl:evaluate() until it returns a result, we reward organisms that make quick decisions, rather than those who finish their fitness tests early. See what I mean?
