### ISSUE TITLE
Parallelize fitness testing across all connected nodes

### ISSUE THREAD

**Issue by dbravender** [dbravender/gerl#2]
This is a no-brainer since gerl was written in Erlang for this very reason. It should be easy to distribute fitness testing.

**Comment by robertdfrench** [comment]
This isn't necessarily trivial. Tournament Selection and Continuous Evaluation methods both require access to multiple organisms  in order to determine fitness of any single individual. This will require some kind of brokering system for checking organisms into/outof the gene pool, but I have some ideas here.

Although for the standard, Koza-style single-organism fitness evaluations, it should be as easy as dividing the Population somewhat evenly among the available nodes and then collecting the fitness scores.

**Comment by dbravender** [comment]
I'm looking back through old issues and I'm going to close this since I'm probably never going to work on this repo again but it does make me want to try something crazy like training a neural network to play a game and then using the neural network as the evaluation function for a GP. The reason I'd want to do this is because the NNs I'm getting even for trivial games with on the order of ~400 bits of input are slow when called thousands of times but an evolved GP might be much more efficient than a neural network. This is probably a pipe dream.
